---

base_locale: en
locales: [en]

data:
  external:
    - "<%= %x[bundle info decidim-core --path].chomp %>/config/locales/%{locale}.yml"
    - "<%= %x[bundle info decidim-proposals --path].chomp %>/config/locales/%{locale}.yml"
    - "<%= %x[bundle info decidim-admin --path].chomp %>/config/locales/%{locale}.yml"
    - "<%= %x[bundle info decidim-participatory_processes --path].chomp %>/config/locales/%{locale}.yml"
    - "<%= %x[bundle info decidim-templates --path].chomp %>/config/locales/%{locale}.yml"

ignore_unused:

ignore_missing:
